plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}
android {
    namespace 'vn.radio.app'
    compileSdk 34
    defaultConfig {
        applicationId "vn.radio.app"
        minSdk 23
        targetSdk 23
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }
    lint { abortOnError false }
}
